#server:
#    port: 3001
spring:
    application:
        name: cloud-eureka
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://localhost:3001/eureka/,http://localhost:3002/eureka/,http://localhost:3003/eureka/
---
spring:
    profiles: uk-3001
server:
    port: 3001
eureka:
    instance:
        hostname: eureka-3001
---
spring:
    profiles: uk-3002
server:
    port: 3002
eureka:
    instance:
        hostname: eureka-3002
---
spring:
    profiles: uk-3003
server:
    port: 3003
eureka:
    instance:
        hostname: eureka-3003